name: Frontend CI/CD

on:
  push:
    branches: [ "main", "pre-prod", intevue-ai-prod ]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        id: vars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "Environment: Production"
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "SERVICE_NAME=interview-app" >> $GITHUB_ENV
            echo "API_URL=https://ksatif-001-site8.atempurl.com/api" >> $GITHUB_ENV
          else
            if [[ $GITHUB_REF == 'refs/heads/intevue-ai-prod' ]]; then
              echo "Environment: Intevueai-Production"
              echo "IMAGE_TAG=intevueaiprod" >> $GITHUB_ENV
              echo "SERVICE_NAME=interview-app-intevueaiprod" >> $GITHUB_ENV
              echo "API_URL=https://ksatif-001-site14.ktempurl.com/api" >> $GITHUB_ENV
            else
              echo "Environment: Pre-Production"
              echo "IMAGE_TAG=preprod" >> $GITHUB_ENV
              echo "SERVICE_NAME=interview-app-preprod" >> $GITHUB_ENV
              echo "API_URL=https://griffin26-001-site6.atempurl.com/api" >> $GITHUB_ENV
          fi

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          # CHANGED: Use key instead of password
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/KloudKoach_UI
            
            git fetch --all
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            docker build \
              --build-arg REACT_APP_API_URL="${{ env.API_URL }}" \
              -t interview-helper:${{ env.IMAGE_TAG }} .

            cd .. 

            docker compose up -d --no-deps ${{ env.SERVICE_NAME }}

            docker image prune -f